//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildContrib.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuildContrib.Tasks.Properties.TaskMessages", typeof(TaskMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes for &quot;{1}&quot; changed to [{0}]..
        /// </summary>
        internal static string Attrib_Comment {
            get {
                return ResourceManager.GetString("Attrib_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3001: Unable to change attributes for file &quot;{0}&quot;. {1}.
        /// </summary>
        internal static string Attrib_Error {
            get {
                return ResourceManager.GetString("Attrib_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3261: Drive {0} is not ready..
        /// </summary>
        internal static string CheckDiskspace_DriveNotReadyError {
            get {
                return ResourceManager.GetString("CheckDiskspace_DriveNotReadyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3263: Drive {0} is running critically low on disk space. The available disk space is {1:D}GB..
        /// </summary>
        internal static string CheckDiskspace_LowDiskspaceCriticalMesssage {
            get {
                return ResourceManager.GetString("CheckDiskspace_LowDiskspaceCriticalMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3262: Drive {0} is running low on disk space. The available disk space is {1:D}GB..
        /// </summary>
        internal static string CheckDiskspace_LowDiskspaceMesssage {
            get {
                return ResourceManager.GetString("CheckDiskspace_LowDiskspaceMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Free Bytes Available: {1:D}GB, Total Number Of Bytes: {2:D}GB, Total Number Of FreeBytes: {3:D}GB..
        /// </summary>
        internal static string CheckDiskspace_Message {
            get {
                return ResourceManager.GetString("CheckDiskspace_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3011: Unable to calculate checksum for file &quot;{0}&quot;. {1}.
        /// </summary>
        internal static string Checksum_Error {
            get {
                return ResourceManager.GetString("Checksum_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3021: Failed to generate code statistics. {0}.
        /// </summary>
        internal static string CodeStats_Error {
            get {
                return ResourceManager.GetString("CodeStats_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals:  [{0}] [T] {1} [C] {2} [E] {3}.
        /// </summary>
        internal static string CodeStats_FileInfo {
            get {
                return ResourceManager.GetString("CodeStats_FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Totals:  [T] {1} [C] {2}  [E] {3}.
        /// </summary>
        internal static string CodeStats_Summary {
            get {
                return ResourceManager.GetString("CodeStats_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings passed to CodeAnalysis task. See output window for details..
        /// </summary>
        internal static string CommandLineSwitchError {
            get {
                return ResourceManager.GetString("CommandLineSwitchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3031: Unable to concatenate file &quot;{0}&quot; to &quot;{1}&quot;. {2}.
        /// </summary>
        internal static string Concat_Error {
            get {
                return ResourceManager.GetString("Concat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3032: Unable to create output file &quot;{0}&quot;. {1}.
        /// </summary>
        internal static string Concat_FailedToCreateOutputFile {
            get {
                return ResourceManager.GetString("Concat_FailedToCreateOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3041: Invalid value &quot;{0}&quot; for &quot;pattern&quot; attribute..
        /// </summary>
        internal static string CreateItemRegex_InvalidPattern {
            get {
                return ResourceManager.GetString("CreateItemRegex_InvalidPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting metadata item &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string CreateItemRegex_Message {
            get {
                return ResourceManager.GetString("CreateItemRegex_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3042: No match found for expression &apos;{0}&apos; in &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string CreateItemRegex_NoMatchFound {
            get {
                return ResourceManager.GetString("CreateItemRegex_NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was not found. Skipping this file..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Analysis Complete -- {0} error(s), {1} warning(s).
        /// </summary>
        internal static string FxCop_AnalysisComplete {
            get {
                return ResourceManager.GetString("FxCop_AnalysisComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read output report: {0}.
        /// </summary>
        internal static string FxCop_FailedReadingReport {
            get {
                return ResourceManager.GetString("FxCop_FailedReadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3051: Unable to locate Microsoft FxCop to perform Code Analysis on managed binaries..
        /// </summary>
        internal static string FxCop_FailedToLocate {
            get {
                return ResourceManager.GetString("FxCop_FailedToLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read Code Analysis output report. Make sure that the directory is writable (default is the project output directory)..
        /// </summary>
        internal static string FxCop_OutputError {
            get {
                return ResourceManager.GetString("FxCop_OutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Code Analysis....
        /// </summary>
        internal static string FxCop_PerformingCodeAnalysis {
            get {
                return ResourceManager.GetString("FxCop_PerformingCodeAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Rule={1}#{2}, Target={3} : {4}.
        /// </summary>
        internal static string FxCop_RuleError {
            get {
                return ResourceManager.GetString("FxCop_RuleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred running Code Analysis. Please contact Microsoft Product Support Services..
        /// </summary>
        internal static string FxCop_UnknownError {
            get {
                return ResourceManager.GetString("FxCop_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3064: Cannot unregister assembly &quot;{0}&quot; - not a valid image. {1}.
        /// </summary>
        internal static string GacUtil_BadImage {
            get {
                return ResourceManager.GetString("GacUtil_BadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3065: Cannot {0} assembly &quot;{1}&quot;. {2}.
        /// </summary>
        internal static string GacUtil_Error {
            get {
                return ResourceManager.GetString("GacUtil_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3065: Cannot {0} assemblies. {1}.
        /// </summary>
        internal static string GacUtil_GeneralError {
            get {
                return ResourceManager.GetString("GacUtil_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3063: Could not load assembly &quot;{0}&quot;. {1}.
        /// </summary>
        internal static string GacUtil_GeneralIoException {
            get {
                return ResourceManager.GetString("GacUtil_GeneralIoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3062: Cannot unregister assembly &quot;{0}&quot; - cannot load file. {1}.
        /// </summary>
        internal static string GacUtil_UnregisterAsmFailedToLoadAssembly {
            get {
                return ResourceManager.GetString("GacUtil_UnregisterAsmFailedToLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3061: Cannot unregister assembly &quot;{0}&quot; - file doesn&apos;t exist. {1}.
        /// </summary>
        internal static string GacUtil_UnregisterAsmFileDoesNotExist {
            get {
                return ResourceManager.GetString("GacUtil_UnregisterAsmFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3997: Failed to create temporary file. {0}.
        /// </summary>
        internal static string General_FailedCreatingTempFile {
            get {
                return ResourceManager.GetString("General_FailedCreatingTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3996: Failed to create temporary file &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string General_FailedCreatingTempFileNamed {
            get {
                return ResourceManager.GetString("General_FailedCreatingTempFileNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3998: Failed to delete temporary file &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string General_FailedDeletingTempFile {
            get {
                return ResourceManager.GetString("General_FailedDeletingTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3995:General text files are not supported. ({0}).
        /// </summary>
        internal static string General_TextFilesNotSupportedExcpetion {
            get {
                return ResourceManager.GetString("General_TextFilesNotSupportedExcpetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3994: &quot;{2}&quot; refers to {0} item(s), and &quot;{3}&quot; refers to {1} item(s). They must have the same number of items..
        /// </summary>
        internal static string General_TwoVectorsMustHaveSameLength {
            get {
                return ResourceManager.GetString("General_TwoVectorsMustHaveSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3071: Unable to retrieve environment information. {0}.
        /// </summary>
        internal static string GetEnvironment_Error {
            get {
                return ResourceManager.GetString("GetEnvironment_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3081: Unable to search files. {0}.
        /// </summary>
        internal static string Grep_Error {
            get {
                return ResourceManager.GetString("Grep_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing matches to &apos;{0}&apos;..
        /// </summary>
        internal static string Grep_OutputFile {
            get {
                return ResourceManager.GetString("Grep_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on FxCop, including where to download the latest version, please go to http://blogs.msdn.com/fxcop/..
        /// </summary>
        internal static string Help_FxCop_FailedToLocate {
            get {
                return ResourceManager.GetString("Help_FxCop_FailedToLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating directory &quot;{0}&quot;..
        /// </summary>
        internal static string Move_CreatesDirectory {
            get {
                return ResourceManager.GetString("Move_CreatesDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3114: Could not move the file &quot;{0}&quot; to the destination file &quot;{1}&quot;, because the destination is a folder instead of a file. To move the source file into a folder, consider using the DestinationFolder parameter instead of DestinationFiles..
        /// </summary>
        internal static string Move_DestinationIsDirectory {
            get {
                return ResourceManager.GetString("Move_DestinationIsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not move from file &quot;{0}&quot; to file &quot;{1}&quot; because the &quot;{2}&quot; parameter was set to &quot;{3}&quot; in the project and the files&apos; sizes and timestamps match..
        /// </summary>
        internal static string Move_DidNotMoveBecauseOfFileMatch {
            get {
                return ResourceManager.GetString("Move_DidNotMoveBecauseOfFileMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3111: Unable to move file &quot;{0}&quot; to &quot;{1}&quot;. {2}.
        /// </summary>
        internal static string Move_Error {
            get {
                return ResourceManager.GetString("Move_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3112: Both &quot;{0}&quot; and &quot;{1}&quot; were specified as input parameters in the project file. Please choose one or the other..
        /// </summary>
        internal static string Move_ExactlyOneTypeOfDestination {
            get {
                return ResourceManager.GetString("Move_ExactlyOneTypeOfDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving file from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string Move_FileComment {
            get {
                return ResourceManager.GetString("Move_FileComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3113: No destination specified for Move. Please supply either &quot;{0}&quot; or &quot;{1}&quot;..
        /// </summary>
        internal static string Move_NeedsDestination {
            get {
                return ResourceManager.GetString("Move_NeedsDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing existing file &quot;{0}&quot;..
        /// </summary>
        internal static string Move_RemovingExistingFile {
            get {
                return ResourceManager.GetString("Move_RemovingExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing read-only attribute from &quot;{0}&quot;..
        /// </summary>
        internal static string Move_RemovingReadOnlyAttribute {
            get {
                return ResourceManager.GetString("Move_RemovingReadOnlyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBC3115: The source file &quot;{0}&quot; is actually a directory.  The &quot;Move&quot; task does not support copying directories..
        /// </summary>
        internal static string Move_SourceIsDirectory {
            get {
                return ResourceManager.GetString("Move_SourceIsDirectory", resourceCulture);
            }
        }
    }
}
