//------------------------------------------------------------------------------
// MSBuildContrib
//
// SolutionInfo.cs
//
// Provides a cental location for Assembly attributes. Assembly attributes
// are values that provide information about an assembly. The attributes are
// divided into the following sets of information:
//
//    * Assembly identity attributes.
//    * Informational attributes.
//    * Assembly manifest attributes.
//    * Strong name attributes.
//
//------------------------------------------------------------------------------
// Copyright (C) 2007-2008 Scott Dorman (sj_dorman@hotmail.com)
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

#region Assembly identity attributes

[assembly: NeutralResourcesLanguage("en-US")]
[assembly: AssemblyInformationalVersion("1.0.2946.8591")]
[assembly: AssemblyFileVersion("1.0.2946.8591")]
[assembly: AssemblyVersion("1.0.0.0")]

#endregion

#region Informational attributes
      
[assembly: AssemblyCompany(@"Scott Dorman")]
[assembly: AssemblyProduct(@"MSBuild Contrib")]
[assembly: AssemblyCopyright(@"Copyright © 2007-2008 Scott Dorman. All rights reserved.")]
[assembly: AssemblyTrademark(@"")]

#endregion

#region Assembly manifest attributes

// Do not use in a globally included SolutionInfo.cs file. The attributes in
// this section apply at an assembly level and should be used in the project
// specific AssemblyInfo.cs files.

#endregion

#region Strong name attributes

// Do not use in a globally included SolutionInfo.cs file. The attributes in
// this section apply at an assembly level and should be used in the project
// specific AssemblyInfo.cs files.

#endregion